### PR TITLE
add id-fixed-int feature

### PR DESCRIPTION
**Pull request by Georges760**

### CODE REVIEW

**Comment by DoumanAsh** [comment]
I'm bit unsure what is meaning behind this feature?

What exactly causes serde-json-core to fail in this case?

**Comment by Georges760** [comment]
it cannot deserialize_any for the Id which is a enum with differents variants. serde-json-core can only do C-like enum.

Having 2 variants (Int and Str) for Id when deserializing imply the use of serde_json.Value like generic type. And serde-json-core specifically does not do that.

**Comment by DoumanAsh** [comment]
Well, it shouldn't handle enums on its own, that's why serde has Visitor trait
so does it mean it panics on calling `deserialie_nay`?

Oh it is https://github.com/rust-embedded-community/serde-json-core/blob/6b88a3ca11e0998afce3b6cde0813e3e9cf78f31/src/de/mod.rs#L351
Kinda bad but I guess I understand


Instead of using feature I guess it is better solved by providing user ability to customize ID type to work around bad deserializer (as standard says ID should be either string or number)

**Comment by DoumanAsh** [comment]
Give me some time to ponder on way to do it.
I don't really like idea of using `feature` for this purpose

**Comment by DoumanAsh** [comment]
@Georges760 I made commit with features based on your idea https://github.com/DoumanAsh/json-rpc-types/commit/1f0ad0604a965b8de69690aaa2bc2015153b6077
Sorry I didn't want to bother you to implement extras, i just wanted to make these features symmetric

Unfrotunately serde API doesn't allow for smart handling of this case so no proper solution can be found without breaking semver.
So let's settle on features.
Please test it and let me know

I will release 1.3.3

**Comment by Georges760** [comment]
Looks great !

Test ok ;)

thanks a lot for your reactivity

**Pull request closed without merging**
