### PR TITLE
let version be omitted when deserializing a request

### PR DESCRIPTION
**Pull request by Georges760**
version is already optional on Response

### CODE REVIEW

**Comment by DoumanAsh** [comment]
This is not actually very good that it is optional on Response.
Do you have particular need for it to be optional?

**Comment by Georges760** [comment]
Unfortunately, yes, many Stratum server send Notification (Request without id) without version field...

**Comment by DoumanAsh** [comment]
This Stratum is awful...
I guess there is no problem to have it as default value, but I really think these guys should consider to actually read JSON-RPC spec, it is not even that long.

Anyway
I will merge and release new version after work today

**Comment by DoumanAsh** [comment]
on side note is this repo with protocol?
https://github.com/aeternity/

If so it is pretty funny:
https://github.com/aeternity/protocol/issues/359

**Review by DoumanAsh — APPROVED** [review]

**Comment by DoumanAsh** [comment]
Released 1.3.4

**Comment by Georges760** [comment]
thx a lot mate

**Pull request merged**
